### PR TITLE
add ARM to user member

### LINKED ISSUE #125: Add ARM Limited as User Member on OpenADx website
Hello, 
Please add ARM Limited as a User Member on the OpenADx working group https://openadx.eclipse.org/members/

ARM

Thank you!

### PR DESCRIPTION
**Pull request by flora8984461**
Fix #125 

Signed-off-by: Yi Liu <yi.liu@eclipse-foundation.org>

### CODE REVIEW

**Comment by autumnfound** [comment]
LGTM, add as reviewer to get sign off + merge. Will wait for description

**Comment by flora8984461** [comment]
> LGTM, add as reviewer to get sign off + merge. Will wait for description

@autumnfound Just confirmed with Zahra on slack and she is good with this, thanks for checking!

**Comment by flora8984461** [comment]
Wait, I just noticed there is already a PR for it https://github.com/EclipseFdn/openadx.eclipse.org/pull/124

**Comment by flora8984461** [comment]
I included the description from this PR https://github.com/EclipseFdn/openadx.eclipse.org/pull/124 .

And I am adding @ariexi to review as well. Thanks!

**Review by ariexi — APPROVED** [review]
Sorry, just saw the review request. Thx!
Best
Andy

**Comment by chrisguindon** [comment]
.. @ariexi and I just notice your comment :)

**Pull request merged**
