### PR TITLE
Updates March2021

### PR DESCRIPTION
**Pull request by ariexi**
Signed-off-by: ariexi <andreas.riexinger@de.bosch.com>

Some necessary updates

### CODE REVIEW

**Comment by ariexi** [comment]
@autumnfound, any idea on how to integrate [twitter timelines](https://developer.twitter.com/en/docs/twitter-for-websites/timelines/overview) and [twitter buttons?](https://developer.twitter.com/en/docs/twitter-for-websites/follow-button/overview)
Thx!
Andy

**Comment by ariexi** [comment]
> 
> 
> @autumnfound, any idea on how to integrate [twitter timelines](https://developer.twitter.com/en/docs/twitter-for-websites/timelines/overview) and [twitter buttons?](https://developer.twitter.com/en/docs/twitter-for-websites/follow-button/overview)
> Thx!
> Andy

@autumnfound, did you had the chance to have a look on my PR? ;-)
Thx!

**Comment by autumnfound** [comment]
> > @autumnfound, any idea on how to integrate [twitter timelines](https://developer.twitter.com/en/docs/twitter-for-websites/timelines/overview) and [twitter buttons?](https://developer.twitter.com/en/docs/twitter-for-websites/follow-button/overview)
> > Thx!
> > Andy
> 
> @autumnfound, did you had the chance to have a look on my PR? ;-)
> Thx!

Looking at your attempts for timeline, I don't know why it wouldn't have worked...it looks pretty straightforward tbh. The button is just a reskin of how they do the timelines, so get that working and this one would be a piece of cake. I'm finishing some stuff up today, but I'll see if I can get this working today in a separate patch!

**Review by autumnfound — APPROVED** [review]

**Comment by autumnfound** [comment]
Apologies for not merging, I hadn't realized you had removed the Twitter things originally, and then we hit end of quarter which was pretty busy for us. I looked it over again and it all looks good so I merged it! I think we need to look at Twitter stuff as a whole in the base theme, as it could be a useful addition!

**Comment by autumnfound** [comment]
Here's the issue for tracking: https://github.com/EclipseFdn/hugo-solstice-theme/issues/218

**Pull request merged**
