### PR TITLE
Updated home page to use newsroom as source of news and events

### PR DESCRIPTION
**Pull request by autumnfound**
Signed-off-by: Martin Lowe <martin.lowe@eclipse-foundation.org>

### CODE REVIEW

**Comment by chrisguindon** [comment]
I am thinking we might want to left-align  "view all" and "submit event" on this page:
https://deploy-preview-88--eclipsefdn-openadx.netlify.app/

**Comment by ariexi** [comment]
@autumnfound @chrisguindon Thanks for implementing!

I guess, this PR replaces issue #76 ?
No further possibility to have past events somewhere?

Thx!

**Comment by chrisguindon** [comment]
@ariexi Our plan is to redirect folks to events.eclipse.org for current and past events. 

We are planning to refresh this website in the next few months and it will be possible to view past events for each WG.

If you wish to host an archive of past events on your site, it's possible.

We can create an /events page and display all openADX events but it's something we are trying to avoid in favor of events.eclipse.org!

**Comment by ariexi** [comment]
@chrisguindon thx for your answer!

Just for my understanding, archive of past events is possible and it is independent from the second point displaying all events?

For me it is fine to have somewhere in time the offer to see the past events as an archive. 
It is not necessary to see all the events on one overview.

But I have an issue with the current view on the OpenADx site, because the events appears side-by-side and not top down ... (as I am not able to post here some pictures, please have a look [here:](https://openadx.eclipse.org/))

And another issue in the News section on the same site, what do I have to do to avoid `&#13` "characters" ?

Thank you so much!

**Comment by autumnfound** [comment]
Regarding display issues...

The current display issue is known and has been mentioned in a different issue (EclipseFdn/jquery-eclipsefdn-api#14). I know what the issue is and will be fixing it this morning! 

The text you are referring to is HTML encoded characters, and was likely a copy-paste error that was fixed in the news item on newsroom.eclipse.org. If you notice things like that, you can likely just send an email to us to let us know to fix it! @chrisguindon as the main driver behind this, you may know more on what we should do regarding content issues?

**Comment by ariexi** [comment]
Thank you so much!

**Pull request merged**
