### PR TITLE
Updates May 2021

### PR DESCRIPTION
**Pull request by ariexi**
Signed-off-by: ariexi <andreas.riexinger@de.bosch.com>

### CODE REVIEW

**Comment by ariexi** [comment]
@chrisguindon @autumnfound, sorry for bothering you, but what should I do to have just the only relevant change in the PR?

I am a bit helpless ...

Thx.
Best,
Andy

**Comment by autumnfound** [comment]
There are 2 things you can try. The first is rebasing like `git fetch origin && git rebase origin/master` assuming that this repos remote is named `origin`. This can be a bit complicated at times, but is useful with bigger branches that would be a pain to redo the change on.

The likely easier option would be to `git fetch origin && git checkout -b ariexi/138 origin/master && git cherry-pick a17440cf282060765ab92b7ead0b154f90433a2e`. What this does is updates your reference, makes a new branch for your change, and uses cherry-pick to pull only that commit into your branch from somewhere else in your local tree. That should give you a new branch (so a new PR), that has a clean history without worrying about rebasing!

**Comment by ariexi** [comment]
@autumnfound, thanks for the hints. I tried the second option and it looks like that something happened, but not the expected one ...
grafik
grafik

But I can´t find the branch ...
Not my day ...

**Comment by ariexi** [comment]
@autumnfound, thanks for the hints. I tried the second option and it looks like that something happened, but not the expected one ...
grafik
grafik

But I can´t find the branch ...
Not my day ...

**Comment by chrisguindon** [comment]
@ariexi I can squash all these commits into one! I will do that! Thanks for the PR.

**Pull request merged**
