### PR TITLE
Zenoh added per OpenADx SC

### PR DESCRIPTION
**Pull request by joespeed**
Zenoh is now an OpenADx project.

### CODE REVIEW

**Comment by joespeed** [comment]
@eclipsewebmaster @ericpoirier

**Comment by autumnfound** [comment]
LGTM, just need a sign-off on the commit from @joespeed to merge it in! :)

**Comment by joespeed** [comment]
> LGTM, just need a sign-off on the commit from @joespeed to merge it in! :)

Great! Please publish before Oct 14th Autoware Foundation TSC meeting. What do you need from @kydos @ariexi @joespeed?

**Comment by ariexi** [comment]
@joespeed, @autumnfound requests the "signed-off" header in your commit, which looks like this:

Signed-off-by: ariexi <andreas.riexinger@de.bosch.com>

Please use your GitHub name as well as your mail address ... ;-)

**Comment by chrisguindon** [comment]
I will merge this change without the sign-off-by.

I can confirm that https://accounts.eclipse.org/users/jspeedn7e has an ECA on file. We strongly recommend the sign-off-by footer but since this is not an Eclipse Projects, we do have the flexibility to merge this as long as the user has an ECA on file.

@joespeed Please try to make sure to include your sign-off-by next time! It will speed things up in regards to code review.

**Pull request merged**
