### PR TITLE
Add arm as a new User member to OpenADx #123

### PR DESCRIPTION
**Pull request by ariexi**
Signed-off-by: ariexi <andreas.riexinger@de.bosch.com>

### CODE REVIEW

**Comment by chrisguindon** [comment]
@ariexi Are all the changes in the PR expected? https://github.com/EclipseFdn/openadx.eclipse.org/pull/124/files

**Comment by flora8984461** [comment]
Hi @ariexi , Since we're not sure if other changes are needed, I have included the description to ARM limited in [my PR](https://github.com/EclipseFdn/openadx.eclipse.org/pull/126) for you to review, thanks!

**Comment by ariexi** [comment]
> @ariexi Are all the changes in the PR expected? https://github.com/EclipseFdn/openadx.eclipse.org/pull/124/files

Hi @chrisguindon , you are right, there is some stuff in, which is not really relevant or merged right now.
So I have to clean up or make a new version...
I am not the best experienced GitHub user ... 😬
Thx!

**Comment by chrisguindon** [comment]
@ariexi No worries!

@flora8984461 did create https://github.com/EclipseFdn/openadx.eclipse.org/pull/126 for this. She did not notice that you had made a patch for this. 

How about we merge her patch instead of you doing it again?

**Comment by chrisguindon** [comment]
This was done via #126

**Pull request closed without merging**
